name: pixel
description: "Una aplicación educativa multiplataforma (Web y Windows) construida en Flutter para ilustrar de forma práctica cómo un simple “píxel” puede cobrar vida a través de la interacción y la animación."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter

  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  http: ^1.5.0
  jocaaguraarchetype: ^3.2.0
  shared_preferences: ^2.5.3
  text_responsive: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
