// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApvTA8L-Y_q0UDpnG2WFBKtl1kpYzSQc',
    appId: '1:970409172645:android:4c2602f64c7d5dafd0774c',
    messagingSenderId: '970409172645',
    projectId: 'pixel-prod-1b8ce',
    storageBucket: 'pixel-prod-1b8ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCxVHAI9qunSAe7AGR-QN0frj6BQJUug',
    appId: '1:970409172645:web:693e47aebcfdffc0d0774c',
    messagingSenderId: '970409172645',
    projectId: 'pixel-prod-1b8ce',
    authDomain: 'pixel-prod-1b8ce.firebaseapp.com',
    storageBucket: 'pixel-prod-1b8ce.firebasestorage.app',
    measurementId: 'G-2T7BDM9SFQ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdCxVHAI9qunSAe7AGR-QN0frj6BQJUug',
    appId: '1:970409172645:web:aeb7924f66f026f9d0774c',
    messagingSenderId: '970409172645',
    projectId: 'pixel-prod-1b8ce',
    authDomain: 'pixel-prod-1b8ce.firebaseapp.com',
    storageBucket: 'pixel-prod-1b8ce.firebasestorage.app',
    measurementId: 'G-3SEGSYSMCF',
  );

}